---
# tasks file for default

- name: Update package system
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Copy file
  ansible.builtin.template:
    src: mutinode.j2
    dest: /home/ubuntu/kolla-ansible/multinode

- name: Copy file
  ansible.builtin.template:
    src: netplan.yml.j2
    dest: /etc/netplan/00-installer-config.yaml
  become: true
# - name: Copy folder 
#   ansible.builtin.copy:
#     src: globals.yml
#     dest: /etc/kolla/globals.yml

- name: Run a net plan apply
  ansible.builtin.shell: |
        sudo netplan apply
  args:
    executable: /bin/bash
  become: true

- name: Edit globals
  ansible.builtin.lineinfile:
    path: /etc/kolla/globals.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: 
    - { regexp: '^#kolla_base_distro:', line: 'kolla_base_distro: "ubuntu"' }
    - { regexp: '^#network_interface:', line: 'network_interface: "eno1"' }
    - { regexp: '^#neutron_external_interface:', line: 'neutron_external_interface: "eno1.{{id_vlan}}"' }
    - { regexp: '^#kolla_internal_vip_address:', line: 'kolla_internal_vip_address: "{{ ip }}"' }
    - { regexp: 'kolla_internal_address:', line: 'kolla_internal_address: "{{ ip }}"' }
    - { regexp: '^#enable_haproxy:', line: 'enable_haproxy: "no"' }
    - { regexp: '^#enable_cinder:', line: 'enable_cinder: "yes"' }
    - { regexp: '^#enable_cinder_backend_lvm:', line: 'enable_cinder_backend_lvm: "yes"' }
