---
# tasks file for default
- name: Update package system
  ansible.builtin.apt:
    update_cache: yes

- name: install python3 and pip3
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3-dev
    - python3-pip
    - libffi-dev
    - gcc
    - libssl-dev
    - python3-venv

- name: Install bottle python package
  ansible.builtin.pip:
    name: virtualenv

- name: Install bottle python package
  ansible.builtin.pip:
    name: pip
    state: latest
    virtualenv: /kolla/venv


- name: Install bottle python package
  ansible.builtin.pip:
    name: ansible-core>=2.14,<2.16
    virtualenv: /kolla/venv
