---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: molecule_ubuntu:jammy
    dockerfile: Dockerfile
    privileged: True
    pre_build_image: False
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    stop_signal: "SIGRTMIN+3"
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - LINUX_IMMUTABLE
      - CAP_NET_BIND_SERVICE
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yaml-lint
